# Generated by Django 5.2.7 on 2026-08-03 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_rental_posted_by_denguelocation_residents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residents',
            name='resident_idCard',
            field=models.ImageField(blank=True, null=True, upload_to='resident_idcards/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
