# Generated by Django 5.2.7 on 2026-08-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_residents_resident_idcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='denguelocation',
            name='barangay',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denguelocation',
            name='purok',
            field=models.TextField(blank=True, null=True),
        ),
    ]
