# Generated by Django 5.2.7 on 2026-05-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_attendance_time_in_alter_attendance_time_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sekyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('role', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
