# Generated by Django 5.2.7 on 2026-08-04 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_denguelocation_barangay_denguelocation_purok'),
    ]

    operations = [
        migrations.CreateModel(
            name='DengueLocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dengue_reports/extra/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dengue_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='api.denguelocation')),
            ],
        ),
    ]
