# Generated by Django 5.2.7 on 2026-07-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_denguelocation_residents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residents',
            name='dengue_status',
            field=models.TextField(default='Safe'),
        ),
    ]
