# Generated by Django 5.2.7 on 2026-07-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_residents_dengue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='denguelocation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dengue_reports/'),
        ),
    ]
