# Generated by Django 5.2.7 on 2026-07-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_denguelocation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='denguelocation',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
