# Generated by Django 5.2.7 on 2026-07-25 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_denguelocation_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residents',
            name='dengue_status',
            field=models.TextField(default='No Dengue History'),
        ),
        migrations.CreateModel(
            name='DengueCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, null=True)),
                ('date_case', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dengue_cases', to='api.residents')),
            ],
        ),
    ]
